server:
  port: 9002

eureka:
  instance:
    hostname: eureka02   # eureka 实例名称
  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false       # 表示自己就是注册中心
    service-url:
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/