server:
  port: 7001
spring:
  application:
    name: gateway-web-01
eureka:
  instance:
    instance-id: gateway-web-01
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      #            defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/