server:
  port: 8081
 
spring:
    application:
        name: user-api

eureka:
    instance:
        instance-id: user-api-8081
        prefer-ip-address: true # 访问路径可以显示 IP
    client:
        service-url:
#            defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
            defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/