server:
  port: 9091
 
spring:
    application:
        name: say-hello

eureka:
    instance:
        instance-id: say-hello-9091
        prefer-ip-address: true # 访问路径可以显示 IP
    client:
        service-url:
#            defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
            defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/